language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hungnguyen/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true hungnguyen/frontend npm run test -- --coverage